export type IngredientType = "bad" | "good";

export type IngredientEntry = {
  slug: string;
  name: string;
  emoji: string;
  type: IngredientType;
  danger?: "high" | "medium" | "low";
  eNumber?: string;
  alsoKnownAs?: string;
  category: string;
  summary: string;        // 1-2 sentence description
  why: string;            // detailed explanation
  scienceFact?: string;
  foundIn?: string;       // common products it appears in
  replacedBy?: string;    // what HolySnacks uses instead
};

export const INGREDIENTS: IngredientEntry[] = [
  // ── BAD INGREDIENTS ───────────────────────────────────────────────────────────
  {
    slug: "high-fructose-corn-syrup",
    name: "High-Fructose Corn Syrup",
    emoji: "⚠️", type: "bad", danger: "high",
    alsoKnownAs: "HFCS, glucose-fructose syrup, isoglucose, corn syrup",
    category: "Sugars & Sweeteners",
    summary: "An industrially produced sweetener derived from corn starch that metabolises differently from natural sugars.",
    why: "Fructose in HFCS bypasses normal insulin signalling and goes directly to the liver, where it's converted to fat (triglycerides). Linked to non-alcoholic fatty liver disease, insulin resistance, obesity, and metabolic syndrome. Has no nutritional value beyond calories.",
    scienceFact: "A landmark 2012 study in PLOS ONE showed fructose-sweetened beverages consumed over 10 weeks significantly increased visceral fat — the dangerous deep belly fat — compared to glucose-sweetened drinks.",
    foundIn: "Soft drinks, candy, cookies, ketchup, salad dressings, bread.",
    replacedBy: "Coconut sugar, dates, raw honey, or organic fruit juice concentrate.",
  },
  {
    slug: "sodium-benzoate",
    name: "Sodium Benzoate",
    emoji: "🧪", type: "bad", danger: "high",
    eNumber: "E211",
    alsoKnownAs: "E211, benzoate of soda",
    category: "Preservatives",
    summary: "A synthetic preservative that when combined with vitamin C (ascorbic acid) can form benzene — a known carcinogen.",
    why: "Sodium benzoate reacts with ascorbic acid (vitamin C) to produce benzene, a Group 1 carcinogen. Also linked to increased hyperactivity in children — the McCann 2007 Southampton Study led to a European ban on mixing it with certain food dyes.",
    scienceFact: "The FDA acknowledged in 2006 that sodium benzoate can form benzene in beverages containing both benzoate and ascorbic acid.",
    foundIn: "Sodas, fruit juices, salad dressings, pickles, condiments.",
    replacedBy: "Rosemary extract, vitamin E (tocopherols), citrus extract.",
  },
  {
    slug: "aspartame",
    name: "Aspartame",
    emoji: "🧪", type: "bad", danger: "high",
    eNumber: "E951",
    alsoKnownAs: "E951, NutraSweet, Equal, Canderel",
    category: "Artificial Sweeteners",
    summary: "A synthetic sweetener 200× sweeter than sugar, classified as 'possibly carcinogenic' by the WHO in 2023.",
    why: "In 2023, the WHO's IARC reclassified aspartame as a Group 2B possible carcinogen. It breaks down into phenylalanine, aspartic acid, and methanol in the body. Studies link it to headaches, gut microbiome disruption, and paradoxically increased appetite and sweet cravings.",
    scienceFact: "A 2022 French cohort study of 100,000+ people found aspartame consumption was associated with a 13% higher cancer risk compared to non-consumers.",
    foundIn: "Diet sodas, sugar-free gum, protein bars, yoghurt, 'light' products.",
    replacedBy: "Stevia leaf extract, monk fruit extract, birch xylitol.",
  },
  {
    slug: "red-40",
    name: "Red 40 (Allura Red)",
    emoji: "🔴", type: "bad", danger: "high",
    eNumber: "E129",
    alsoKnownAs: "E129, Allura Red AC, FD&C Red #40",
    category: "Artificial Colors",
    summary: "A petroleum-derived red food dye linked to hyperactivity in children and banned in several countries.",
    why: "Derived from coal tar or petroleum. Part of the Southampton Six — a group of artificial colours the UK FSA linked to increased hyperactivity in children. Requires a warning label in the EU ('may have an adverse effect on activity and attention in children'). Banned in Denmark, Belgium, France, Switzerland, and Sweden.",
    foundIn: "Candy, fruit punch, sports drinks, maraschino cherries, gummies.",
    replacedBy: "Beet juice powder, lycopene, carmine (for non-vegan), paprika extract.",
  },
  {
    slug: "yellow-5",
    name: "Yellow 5 (Tartrazine)",
    emoji: "🟡", type: "bad", danger: "high",
    eNumber: "E102",
    alsoKnownAs: "E102, Tartrazine, FD&C Yellow #5",
    category: "Artificial Colors",
    summary: "A synthetic yellow azo dye derived from petroleum, part of the Southampton Six hyperactivity dyes.",
    why: "One of the six dyes in the 2007 Southampton Study that showed a statistically significant increase in hyperactivity in children. Requires a mandatory warning label in the EU. Linked to asthma, hives, and migraines in sensitive individuals. Produced from petroleum.",
    foundIn: "Mountain Dew, Fanta, pickles, chips, mac and cheese, sweets.",
    replacedBy: "Turmeric, saffron extract, beta-carotene.",
  },
  {
    slug: "monosodium-glutamate",
    name: "Monosodium Glutamate (MSG)",
    emoji: "🧂", type: "bad", danger: "medium",
    eNumber: "E621",
    alsoKnownAs: "E621, MSG, glutamate, monosodium L-glutamate",
    category: "Flavour Enhancers",
    summary: "A synthetic flavour enhancer that stimulates glutamate receptors to make food taste more savoury and addictive.",
    why: "MSG bypasses natural satiety signals by directly stimulating the brain's glutamate receptors. Studies link high MSG consumption to increased appetite, weight gain, and headaches (Chinese Restaurant Syndrome, though contested). Many sensitive individuals report neurological symptoms.",
    foundIn: "Crisps, instant noodles, fast food, soups, seasonings.",
    replacedBy: "Nutritional yeast, mushroom powder, natural herbs and spices.",
  },
  {
    slug: "carrageenan",
    name: "Carrageenan",
    emoji: "🌊", type: "bad", danger: "medium",
    eNumber: "E407",
    alsoKnownAs: "E407, Irish moss extract",
    category: "Thickeners & Stabilisers",
    summary: "A seaweed-derived thickener that despite its natural origin is linked to gut inflammation and IBS.",
    why: "Despite being derived from seaweed, carrageenan's polysaccharide structure promotes inflammation in the gut lining. Animal studies show it triggers ulceration at exposures equivalent to typical human consumption. The Cornucopia Institute petitioned the FDA to remove it from organic foods.",
    scienceFact: "Joanne Tobacman's 1981–2012 research showed carrageenan reliably causes intestinal inflammation and ulceration in animal models at doses comparable to human dietary exposure.",
    foundIn: "Almond milk, yoghurt, chocolate milk, deli meats, infant formula.",
    replacedBy: "Guar gum, sunflower lecithin, or simply nothing.",
  },
  {
    slug: "titanium-dioxide",
    name: "Titanium Dioxide",
    emoji: "⬜", type: "bad", danger: "high",
    eNumber: "E171",
    alsoKnownAs: "E171, TiO2, CI 77891",
    category: "Colors & Whiteners",
    summary: "A whitening agent now banned as a food additive in the EU following evidence of genotoxicity.",
    why: "The European Food Safety Authority (EFSA) concluded in 2021 that titanium dioxide can no longer be considered safe as a food additive. The nanoparticles accumulate in organs, cannot be eliminated by the body, and EFSA found it 'genotoxic' — capable of damaging DNA. Banned in EU food since August 2022.",
    foundIn: "White candies, chewing gum, icing, powdered donuts, medications.",
    replacedBy: "Nothing — natural foods simply don't need to be white.",
  },
  {
    slug: "bha-bht",
    name: "BHA & BHT",
    emoji: "⚗️", type: "bad", danger: "high",
    alsoKnownAs: "Butylated hydroxyanisole, butylated hydroxytoluene, E320, E321",
    category: "Synthetic Preservatives",
    summary: "Petrochemical antioxidant preservatives listed as reasonably anticipated human carcinogens.",
    why: "BHA is listed as a probable human carcinogen by the US National Toxicology Program. BHT is listed as 'reasonably anticipated to be a human carcinogen.' Both are derived from petroleum and banned or restricted in food in Japan, UK, and EU at various levels.",
    foundIn: "Breakfast cereals, chewing gum, snack foods, vegetable oils, preserved meats.",
    replacedBy: "Rosemary extract, vitamin E (tocopherol), ascorbyl palmitate.",
  },
  {
    slug: "trans-fat",
    name: "Trans Fat (Hydrogenated Oil)",
    emoji: "🚫", type: "bad", danger: "high",
    alsoKnownAs: "Partially hydrogenated oil, PHO, hydrogenated vegetable oil",
    category: "Fats & Oils",
    summary: "Industrially produced fats that raise LDL ('bad') cholesterol and lower HDL ('good') cholesterol.",
    why: "Trans fats are the only nutrient with no safe level of consumption according to the WHO. Consuming 2g/day increases heart disease risk by 23%. Banned or restricted in many countries. Even 'zero trans fat' labels can contain 0.5g per serving due to rounding rules.",
    scienceFact: "The Harvard Nurses' Health Study estimated that replacing 2% of energy from trans fat with polyunsaturated fat would reduce heart disease by 53%.",
    foundIn: "Margarine, fried fast food, commercial baked goods, some microwave popcorn.",
    replacedBy: "Cold-pressed olive oil, virgin coconut oil, natural butter.",
  },
  {
    slug: "potassium-sorbate",
    name: "Potassium Sorbate",
    emoji: "🧫", type: "bad", danger: "low",
    eNumber: "E202",
    alsoKnownAs: "E202, sorbic acid potassium salt",
    category: "Preservatives",
    summary: "A synthetic preservative considered generally safe at current levels, but linked to genotoxicity in some cell studies.",
    why: "While GRAS-listed and used widely, potassium sorbate has been shown in cell culture studies to be genotoxic to human lymphocytes. Converts to sorbic acid in the body. Some individuals report skin irritation and allergic reactions. Not necessary when products are naturally preserved.",
    foundIn: "Cheese, wine, dried fruit, baked goods, condiments.",
    replacedBy: "Rosemary extract, naturally acidic environments (citric acid), vitamin E.",
  },
  {
    slug: "maltodextrin",
    name: "Maltodextrin",
    emoji: "🌽", type: "bad", danger: "medium",
    category: "Fillers & Binders",
    summary: "A highly processed carbohydrate filler with a higher glycaemic index than table sugar.",
    why: "Maltodextrin has a GI of 95–136 (table sugar is 65), causing rapid blood sugar spikes. It feeds pathogenic gut bacteria and reduces beneficial microbial diversity. Derived from corn, wheat, potato, or tapioca starch via acid and enzyme hydrolysis.",
    scienceFact: "A 2012 study in PLOS ONE showed maltodextrin consumption promotes growth of E. coli biofilms in the gut and suppresses anti-inflammatory bacterial populations.",
    foundIn: "Protein powders, chips, candy, instant sauces, sports drinks.",
    replacedBy: "Nothing — if it's in the ingredients, it's a filler that serves no nutritional purpose.",
  },

  // ── GOOD INGREDIENTS ──────────────────────────────────────────────────────────
  {
    slug: "nano-hydroxyapatite",
    name: "Nano-Hydroxyapatite",
    emoji: "🦷", type: "good",
    alsoKnownAs: "n-HA, NHA, hydroxyapatite",
    category: "Dental Health",
    summary: "The exact mineral your teeth are made of — remineralises enamel at the nano scale.",
    why: "Nano-hydroxyapatite is a biomimetic mineral identical in composition to tooth enamel. At nano scale it penetrates and fills microscopic enamel defects, reversing early decay. Clinically proven fluoride alternative used in Japanese dentistry since the 1980s. Unlike fluoride, it's safe to swallow.",
    scienceFact: "A 2019 systematic review in the Journal of Dentistry found nano-hydroxyapatite equal to fluoride in caries prevention with zero toxicity concerns.",
    replacedBy: "Fluoride (which it replaces as a safer, equally effective alternative).",
  },
  {
    slug: "birch-xylitol",
    name: "Birch Xylitol",
    emoji: "🌿", type: "good",
    alsoKnownAs: "Xylitol, birch sugar",
    category: "Natural Sweeteners",
    summary: "A plant-derived sugar alcohol that actively fights tooth decay and has zero glycaemic impact.",
    why: "Xylitol cannot be metabolised by oral bacteria (Streptococcus mutans), starving them and reducing cavity formation by up to 40%. Has a GI of 7 vs 65 for sugar. Derived from birch trees — a natural, sustainable process. Unlike corn-based xylitol, birch xylitol avoids GMO concerns.",
    scienceFact: "A Cochrane Review (2015) found xylitol chewing gum reduces S. mutans counts in saliva by 50% and reduces caries incidence in children by 40%.",
  },
  {
    slug: "apple-pectin",
    name: "Apple Pectin",
    emoji: "🍎", type: "good",
    alsoKnownAs: "Pectin, fruit pectin, E440",
    category: "Natural Gelling Agents",
    summary: "A soluble prebiotic fibre from apple skins that feeds beneficial gut bacteria and reduces cholesterol.",
    why: "Apple pectin is a prebiotic fibre that selectively feeds Lactobacillus and Bifidobacterium — the beneficial bacteria in your gut. Reduces LDL cholesterol by binding bile acids. Slows glucose absorption, reducing post-meal blood sugar spikes. Creates a gummy texture without gelatin, corn syrup, or synthetic binders.",
    scienceFact: "A meta-analysis of 67 trials found pectin reduced LDL cholesterol by an average of 7% — comparable to certain medications.",
  },
  {
    slug: "organic-stevia",
    name: "Organic Stevia Leaf Extract",
    emoji: "🌱", type: "good",
    alsoKnownAs: "Stevia, rebaudioside A, steviol glycosides, E960",
    category: "Natural Sweeteners",
    summary: "A zero-calorie, zero-GI sweetener from the Stevia rebaudiana plant — 300× sweeter than sugar.",
    why: "Stevia has been safely used in South America for 1,500 years. Zero calories, zero glycaemic response, and zero insulin effect. Whole-leaf extract contains multiple beneficial compounds including antioxidant diterpenes. The WHO has declared it safe for all populations including diabetics.",
    scienceFact: "Studies show steviol glycosides may actually improve insulin sensitivity — the opposite of what artificial sweeteners do.",
  },
  {
    slug: "rosemary-extract",
    name: "Rosemary Extract",
    emoji: "🌿", type: "good",
    alsoKnownAs: "Rosemary antioxidant, E392, rosmarinic acid",
    category: "Natural Preservatives",
    summary: "A potent natural antioxidant that replaces synthetic BHA and BHT with zero health concerns.",
    why: "Rosemary extract contains rosmarinic acid and carnosic acid — among the strongest natural antioxidants known. Prevents oxidative rancidity in oils and fats just as effectively as BHA/BHT without the carcinogen concerns. Also has anti-inflammatory, antimicrobial, and neuroprotective properties.",
    scienceFact: "Carnosic acid in rosemary has shown in studies to protect brain cells from oxidative stress, suggesting potential neuroprotective benefits beyond its role as a preservative.",
  },
  {
    slug: "turmeric",
    name: "Turmeric",
    emoji: "💛", type: "good",
    alsoKnownAs: "Curcumin, curcuma longa, E100",
    category: "Natural Colors & Superfoods",
    summary: "A golden spice with over 3,000 published studies on its anti-inflammatory compound curcumin.",
    why: "Curcumin, the active compound in turmeric, is one of the most-studied natural anti-inflammatory molecules. It inhibits NF-κB — the master switch for inflammation — more broadly than many anti-inflammatory drugs. Also functions as a natural yellow dye, replacing tartrazine (E102) with zero safety concerns.",
    scienceFact: "A 2020 meta-analysis of 23 RCTs found curcumin supplementation significantly reduced CRP (C-reactive protein, the main inflammation marker) versus placebo.",
  },
  {
    slug: "coconut-sugar",
    name: "Coconut Sugar",
    emoji: "🥥", type: "good",
    alsoKnownAs: "Coconut palm sugar, gula melaka, palm sugar",
    category: "Natural Sweeteners",
    summary: "An unrefined natural sweetener with a GI of 35 (vs 65 for white sugar) and genuine mineral content.",
    why: "Unlike refined sugar which is stripped of all nutrients, coconut sugar retains iron, zinc, calcium, potassium, and up to 9% inulin — a prebiotic fibre that feeds beneficial gut bacteria. Its lower GI produces a gentler blood sugar response. Sustainably tapped from coconut palms without harming the trees.",
    scienceFact: "Coconut sugar contains 400× more potassium and 1000× more zinc than white cane sugar — minerals completely removed during refining.",
  },
  {
    slug: "spirulina",
    name: "Spirulina",
    emoji: "💚", type: "good",
    alsoKnownAs: "Spirulina powder, blue-green algae, phycocyanin, E6",
    category: "Superfoods & Natural Colors",
    summary: "A blue-green microalgae with all essential amino acids, more protein per gram than beef, and potent antioxidant pigments.",
    why: "Spirulina is one of Earth's most nutrient-dense foods. Contains 60–70% protein by dry weight, all essential amino acids, B12, iron, and the antioxidant phycocyanin — which gives it its blue-green colour and protects cells from oxidative damage. Used as a natural blue-green food colouring in place of synthetic dyes.",
    scienceFact: "A 2016 systematic review found spirulina supplementation significantly reduced fasting blood glucose, LDL cholesterol, and blood pressure in type 2 diabetics.",
  },
  {
    slug: "probiotics",
    name: "Live Probiotics & Cultures",
    emoji: "🦠", type: "good",
    alsoKnownAs: "Lactobacillus, Bifidobacterium, live cultures, acidophilus",
    category: "Gut Health",
    summary: "Beneficial bacteria that support gut microbiome diversity, immunity, and the gut-brain connection.",
    why: "Your gut microbiome — 100 trillion bacteria — influences immunity, mood, weight, and metabolism. Probiotics increase diversity and support beneficial strains like Lactobacillus and Bifidobacterium. Genuine clinical evidence for IBS relief, immune support, and even mood regulation via the gut-brain axis.",
    scienceFact: "A 2019 Lancet meta-analysis of 63 RCTs found probiotics reduce antibiotic-associated diarrhoea by 51% and reduce the risk of Clostridium difficile infection by 60%.",
  },
];

export function getIngredientBySlug(slug: string): IngredientEntry | null {
  return INGREDIENTS.find((i) => i.slug === slug) ?? null;
}

export const BAD_INGREDIENTS = INGREDIENTS.filter((i) => i.type === "bad");
export const GOOD_INGREDIENTS = INGREDIENTS.filter((i) => i.type === "good");
